include: package:very_good_analysis/analysis_options.yaml
analyzer:
  errors:
    unnecessary_await_in_return: ignore
  exclude:
    - lib/l10n/gen/*
linter:
  rules:
    public_member_api_docs: false
